### PR TITLE
Update format.js

### PR DESCRIPTION
**Pull request by AaronRutledge**
Update to fix sign for values < 1'

### CODE REVIEW

**Review by AaronRutledge — COMMENTED** [review]
fixed for less than 0.

**Comment by dobriai** [comment]
Nice catch! Thanks a lot!
The code fix is fine, I would just prefer to massage it in a slightly different way - take a look at branch `pr1` in my repo - I just pushed it. This is how I want it, unless you see a problem there :-)

**After that:** If you want to have your name in the history, i.e. get the credit, which you deserve, there are two choices:
1. I can pull this PR "as is" and then make the tweaks
2. Or, you can copy the changes from branch `pr1` and push them here. Then I pull.

I am perfectly fine either way - just let know.

In case you completely don't care, I will just merge branch `pr1` from my repo into `master`.

**Comment by AaronRutledge** [comment]
You are very welcome.  Your library has saved me a ton of time, so very
happy to make a small contribution!  If only we could all be on metric and
forget this crazy fractional length stuff.
I don't care too much about the credit.  If you pull mine in and make the
tweaks, that works just fine--or if you want to just merge your
branch--that is fine too.
Note: I made a separate pull request for parse as well for a similar
issue.  You probably want to massage that as well.
Again, I ma very appreciative of your work and thanks a lot for updating.

**Comment by dobriai** [comment]
I am quite glad to hear that this came to be useful to anyone! It's been a while that I wrote it and have not followed much on how much it is being used.

Fork over the other PR. I'll review it asap.
Then, I suppose I should bump the version too.
I'll try to wrap it up by the end of the week/weekend.

**Comment by AaronRutledge** [comment]
Sounds great.
Here is the other pull request for parse:
https://github.com/dobriai/footinch/pull/2/commits/471a2be1ab6fa28ef9e21cb7f7efc053ba2d452d

BTW:  Do you happen to work in the architecture/construction world?

Thanks again, Aaron

**Comment by dobriai** [comment]
I do - autodesk. Why would otherwise anyone ever bother with feet and inches :-)

**Pull request merged**
